### ISSUE TITLE
Upgrade http 0.2 to 1.0.0 and http-body 0.4 to 1.0.0

### ISSUE THREAD

**Issue by ghost** [User65k/async-fcgi#8]
I would appreciate if you could upgrade http 0.2 to 1.0 and http-body 0.4 to 1.0 I need to use http 1.0 because I use hyper 1.2.

**Comment by User65k** [comment]
There is now also a Release for it and it is on crates.
https://github.com/User65k/async-fcgi/releases/tag/v0.5
